import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Supabase: invitados no pueden aprobar ni leer pendientes; administración y cuotas',async()=>{
 const db=new PGlite();
 const guest='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',admin='33333333-3333-4333-8333-333333333333';
 const as=async(role,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role);};
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth,storage to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant select,insert,delete on storage.objects to anon,authenticated;
 insert into auth.users values('${guest}'),('${other}'),('${admin}');`);
 await db.exec(await readFile('supabase-schema.sql','utf8'));
 await db.query('insert into vf_admins values($1)',[admin]);
 await as('authenticated',guest);
 await assert.rejects(()=>db.query("select vf_reserve_photo('Ana','Feliz cumple')"),/no está recibiendo/);
 await as('authenticated',admin);
 await db.exec('update vf_settings set open=true');
 await as('authenticated',guest);
 const {rows:[{photo}]}=await db.query("select vf_reserve_photo('Ana','Feliz cumple') photo");
 await assert.rejects(()=>db.exec("insert into vf_admins values('"+guest+"')"),/permission denied/);
 await assert.rejects(()=>db.query('select * from vf_list_photos(true)'),/Acceso denegado/);
 await assert.rejects(()=>db.query('select vf_finish_photo($1)',[photo.id]),/no se terminó/);
 await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['birthday-photos',photo.path]);
 await db.query('select vf_finish_photo($1)',[photo.id]);
 assert.equal((await db.query('select * from vf_list_photos(false)')).rows.length,0);
 await db.query("update vf_photos set status='approved' where id=$1",[photo.id]);
 assert.equal((await db.query('select * from vf_list_photos(false)')).rows.length,0);
 await as('anon');assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await as('authenticated',other);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(()=>db.query('select vf_finish_photo($1)',[photo.id]),/no se terminó/);
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['birthday-photos',photo.path]),/row-level security/);
 await as('authenticated',admin);
 assert.equal((await db.query('select * from vf_list_photos(true)')).rows[0].status,'pending');
 await db.query("update vf_photos set status='approved' where id=$1",[photo.id]);
 await as('anon');assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 await as('authenticated',guest);await db.query("select vf_react($1,'❤️')",[photo.id]);
 await assert.rejects(()=>db.query("select vf_react($1,'✨')",[photo.id]),/Esperá/);
 assert.equal((await db.query('select * from vf_list_photos(false)')).rows[0].reactions['❤️'],1);
 for(let i=1;i<30;i++)await db.query("select vf_reserve_photo('Ana','')");
 await assert.rejects(()=>db.query("select vf_reserve_photo('Ana','')"),/muchas fotos/);
 await as('authenticated',admin);await db.query("update vf_photos set status='hidden' where id=$1",[photo.id]);
 await as('anon');assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 }finally{await db.close();}
});
