import express from 'express';
import multer from 'multer';
import sharp from 'sharp';
import QRCode from 'qrcode';
import { rateLimit } from 'express-rate-limit';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { mkdirSync, existsSync } from 'node:fs';
import { writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const data=path.resolve(process.env.DATA_DIR||path.join(root,'data'));
mkdirSync(path.join(data,'photos'),{recursive:true});
const password=process.env.ADMIN_PASSWORD;
if(!password||password.length<12) throw Error('Configurá ADMIN_PASSWORD con al menos 12 caracteres en .env');
const db=new DatabaseSync(path.join(data,'event.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS photos(id TEXT PRIMARY KEY,name TEXT,caption TEXT,status TEXT,created INTEGER);
CREATE TABLE IF NOT EXISTS reactions(photo TEXT REFERENCES photos(id) ON DELETE CASCADE,visitor TEXT,emoji TEXT,PRIMARY KEY(photo,visitor));
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
INSERT OR IGNORE INTO settings VALUES('moderation','true'),('open','true'),('seconds','8');`);
const app=express(); app.disable('x-powered-by');
if(process.env.TRUST_PROXY) app.set('trust proxy',Number(process.env.TRUST_PROXY));
app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY'});next();});
app.use(express.json({limit:'16kb'}));
const sessions=new Map(),clients=new Set();
const settings=()=>Object.fromEntries(db.prepare('SELECT * FROM settings').all().map(r=>[r.key,JSON.parse(r.value)]));
const equal=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&timingSafeEqual(x,y);};
function session(req){const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('vf_session='))?.slice(11);return token&&sessions.get(token)>Date.now();}
function admin(req,res,next){if(!session(req)) return res.status(401).json({error:'Iniciá sesión para administrar.'});next();}
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD'].includes(req.method)&&req.headers.origin&&req.headers.origin!==new URL(process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`).origin)return res.status(403).json({error:'Origen no permitido.'});next();});
const broadcast=(type,payload={})=>{for(const res of clients)res.write(`event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`);};
app.get('/api/events',(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders();res.write('retry: 3000\n\n');clients.add(res);const timer=setInterval(()=>res.write(': ping\n\n'),20000);req.on('close',()=>{clients.delete(res);clearInterval(timer);});});
app.get('/api/config',(req,res)=>res.json({...settings(),title:'Bianca',date:'11 · 10 · 2026',guestUrl:process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`}));
app.get('/api/qr',async(req,res)=>{const url=process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`;res.type('png').send(await QRCode.toBuffer(url,{width:640,margin:3,color:{dark:'#302519',light:'#ffffff'}}));});
function photos(all=false){return db.prepare(`SELECT * FROM photos ${all?'':"WHERE status='approved'"} ORDER BY created DESC`).all().map(p=>({...p,url:`/media/${p.id}`,reactions:Object.fromEntries(db.prepare('SELECT emoji,count(*) AS n FROM reactions WHERE photo=? GROUP BY emoji').all(p.id).map(r=>[r.emoji,r.n]))}));}
app.get('/api/photos',(req,res)=>res.json(photos()));
app.get('/media/:id',(req,res)=>{const p=db.prepare('SELECT * FROM photos WHERE id=?').get(req.params.id);if(!p||(p.status!=='approved'&&!session(req)))return res.sendStatus(404);res.set('Cache-Control','no-store');res.sendFile(path.join(data,'photos',`${p.id}.jpg`));});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024,files:1,fields:3},fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(file.mimetype))});
app.post('/api/photos',rateLimit({windowMs:60000,limit:Number(process.env.UPLOADS_PER_MINUTE||120),standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Esperá un minuto antes de subir más fotos.'}}),(req,res,next)=>settings().open?next():res.status(403).json({error:'La carga de fotos está cerrada.'}),upload.single('photo'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'Elegí una foto JPG, PNG o WebP.'});if(db.prepare('SELECT count(*) AS n FROM photos').get().n>=Number(process.env.MAX_PHOTOS||3000))return res.status(409).json({error:'El álbum alcanzó su capacidad. Avisá a la organización.'});let buffer;try{buffer=await sharp(req.file.buffer,{limitInputPixels:50000000}).rotate().resize({width:2200,height:2200,fit:'inside',withoutEnlargement:true}).jpeg({quality:86}).toBuffer();}catch{return res.status(400).json({error:'No pudimos leer esta foto. Probá exportarla como JPG.'});}const id=randomUUID(),status=settings().moderation?'pending':'approved';await writeFile(path.join(data,'photos',`${id}.jpg`),buffer);db.prepare('INSERT INTO photos VALUES(?,?,?,?,?)').run(id,String(req.body.name||'Invitado').trim().slice(0,50)||'Invitado',String(req.body.caption||'').slice(0,140),status,Date.now());broadcast('refresh');res.status(201).json({id,status});}catch(e){next(e);}});
const emojis=['❤️','😍','👏','🎉','✨'];
app.post('/api/photos/:id/reactions',rateLimit({windowMs:60000,limit:80,message:{error:'Esperá un momento para volver a reaccionar.'}}),(req,res)=>{const {visitor,emoji}=req.body;if(!/^[a-zA-Z0-9-]{16,80}$/.test(visitor||'')||!emojis.includes(emoji))return res.status(400).json({error:'Reacción inválida.'});if(!db.prepare("SELECT id FROM photos WHERE id=? AND status='approved'").get(req.params.id))return res.sendStatus(404);db.prepare('INSERT INTO reactions VALUES(?,?,?) ON CONFLICT(photo,visitor) DO UPDATE SET emoji=excluded.emoji').run(req.params.id,visitor,emoji);broadcast('reaction',{id:req.params.id,emoji});res.json({ok:true});});
app.post('/api/login',rateLimit({windowMs:15*60000,limit:10,message:{error:'Demasiados intentos. Volvé a intentar en 15 minutos.'}}),(req,res)=>{if(!equal(req.body.password,password))return res.status(401).json({error:'Contraseña incorrecta.'});const token=randomBytes(32).toString('hex');sessions.set(token,Date.now()+12*3600000);res.cookie('vf_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.PUBLIC_URL?.startsWith('https://')||false,maxAge:12*3600000});res.json({ok:true});});
app.post('/api/logout',(req,res)=>{const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('vf_session='))?.slice(11);sessions.delete(token);res.clearCookie('vf_session');res.json({ok:true});});
app.get('/api/admin/photos',admin,(req,res)=>res.json(photos(true)));
app.patch('/api/admin/photos/:id',admin,(req,res)=>{if(!['approved','hidden'].includes(req.body.status))return res.sendStatus(400);const result=db.prepare('UPDATE photos SET status=? WHERE id=?').run(req.body.status,req.params.id);if(!result.changes)return res.sendStatus(404);broadcast('refresh');res.json({ok:true});});
app.delete('/api/admin/photos/:id',admin,async(req,res,next)=>{try{if(!/^[0-9a-f-]{36}$/.test(req.params.id))return res.sendStatus(400);db.prepare('DELETE FROM photos WHERE id=?').run(req.params.id);await unlink(path.join(data,'photos',`${req.params.id}.jpg`)).catch(e=>{if(e.code!=='ENOENT')throw e;});broadcast('refresh');res.json({ok:true});}catch(e){next(e);}});
app.patch('/api/admin/settings',admin,(req,res)=>{const s=req.body;if(typeof s.open!=='boolean'||typeof s.moderation!=='boolean'||!Number.isInteger(s.seconds)||s.seconds<4||s.seconds>30)return res.status(400).json({error:'Configuración inválida.'});for(const key of ['open','moderation','seconds'])db.prepare('UPDATE settings SET value=? WHERE key=?').run(JSON.stringify(s[key]),key);broadcast('config');res.json(settings());});
app.get('/health',(req,res)=>res.json({ok:true}));
app.use(express.static(path.join(root,'public')));
for(const route of ['/pantalla','/admin','/qr'])app.get(route,(req,res)=>res.sendFile(path.join(root,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err.message);res.status(err instanceof multer.MulterError?400:500).json({error:err.code==='LIMIT_FILE_SIZE'?'La foto supera los 15 MB.':'No se pudo completar la operación. Intentá nuevamente.'});});
const server=app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log(`Veamoslasfotos listo en puerto ${server.address().port}`));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{for(const c of clients)c.end();server.close(()=>{db.close();process.exit(0);});});
